version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - ./gestion-produits/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  produits:
    build:
      context: ./gestion-produits
    container_name: produits_container
    restart: always
    env_file:
      - ./gestion-produits/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  commandes:
    build:
      context: ./gestion-commandes
    container_name: commandes_container
    restart: always
    env_file:
      - ./gestion-commandes/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres_data: