apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-commandes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-commandes
  template:
    metadata:
      labels:
        app: api-commandes
    spec:
      containers:
        - name: api-commandes
          image: gestion-commandes-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_DB
              value: "produits_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"